- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop: 
    - my sql
    - nginx
    - postfix
